env:
  device: null                          # (None or str): specifies the device to be used if running on the gpu with torch backend
  automatic_reset: false                # (bool): whether to automatic reset after an episode finishes
  flatten_action_space: false           # (bool): whether to flatten the action space as a sinle 1D-array
  flatten_obs_space: false              # (bool): whether the observation space should be flattened when generated
  use_external_obs: false               # (bool): Whether to use external observations or not
  initial_pos_z_offset: 0.1
  external_sensors:                     # (None or list): If specified, list of sensor configurations for external sensors to add. Should specify sensor "type" and any additional kwargs to instantiate the sensor. Each entry should be the kwargs passed to @create_sensor, in addition to position, orientation
    - sensor_type: VisionSensor
      name: external_sensor0
      relative_prim_path: /external_sensor0
      modalities: [rgb, depth]
      sensor_kwargs:
        image_height: 128
        image_width: 128
      position: [0, 0, 1.0]
      orientation: [0.707, 0.0, 0.0, 0.707]
      pose_frame: parent


render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: InteractiveTraversableScene
  scene_model: house_double_floor_lower
  trav_map_resolution: 0.1
  default_erosion_radius: 0.0
  trav_map_with_objects: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  load_object_categories: null
  not_load_object_categories: null
  load_room_types: ['living_room']
  load_room_instances: null
  seg_map_resolution: 1.0
  scene_source: OG
  include_robots: true

robots:
  - type: Tiago
    obs_modalities: [rgb]
    include_sensor_names: null
    exclude_sensor_names: null
    scale: 1.0
    self_collisions: true
    action_normalize: false
    action_type: continuous
    grasping_mode: sticky
    reset_joint_pos: [
      0.0000,
      0.0000,
      -0.0000,
      -0.0000,
      -0.0000,
      -0.0000,
      0.3500,
      0.9052,
      0.9052,
      0.0000,
      -0.4281,
      -0.4281,
      -0.4500,
      2.2350,
      2.2350,
      1.6463,
      1.6463,
      0.7687,
      0.7687,
      -0.7946,
      -0.7946,
      -1.0891,
      -1.0891,
      0.0450,
      0.0450,
      0.0450,
      0.0450,
    ]
    sensor_config:
      VisionSensor:
        sensor_kwargs:
          image_height: 128
          image_width: 128
    controller_config:
      base:
        name: HolonomicBaseJointController
        motor_type: position
        command_input_limits: null
        use_impedances: false
      trunk:
        name: JointController
        motor_type: position
        command_input_limits: null
        use_delta_commands: false
        use_impedances: false
      arm_left:
        name: JointController
        motor_type: position
        command_input_limits: null
        use_delta_commands: false
        use_impedances: False
      arm_right:
        name: JointController
        motor_type: position
        command_input_limits: null
        use_delta_commands: false
        use_impedances: false
      gripper_left:
        name: JointController
        motor_type: position
        command_input_limits: null
        use_delta_commands: false
        use_impedances: false
      gripper_right:
        name: JointController
        motor_type: position
        command_input_limits: null
        use_delta_commands: false
        use_impedances: false
      camera:
        name: JointController
        motor_type: position
        command_input_limits: null
        use_delta_commands: false
        use_impedances: false

objects: []

task:
  type: BehaviorTask
  activity_name: picking_up_trash
  activity_definition_id: 0
  activity_instance_id: 0
  predefined_problem: null
  online_object_sampling: true
  debug_object_sampling: null
  highlight_task_relevant_objects: false
  use_presampled_robot_pose: false
  termination_config:
    max_steps: 500
  reward_config:
    r_potential: 1.0